title:            Студсовет мехмата МГУ
description:      Представляем и защищаем интересы студентов мехмата

# put your disqus here
disqus_shortname:
reading_time:      false # if true, shows the estimated reading time for a post
words_per_minute:  200
logo:              images/logo.png # logo visible in the topbar
excerpt_separator: <!--more-->
share:             false
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: http://studmm.ru

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Главная'
    url: '/'
  - title: 'Новости'
    url: '/news'
  - title: 'О нас'
    url: '/about'
  - title: 'Группы'
    submenu:
      - title: 'Образование'
        url: '/'
      - title: 'Бытовые вопросы'
        url: '/'
      - title: 'Праздники'
        url: '/'
      - title: 'Оповещение'
        url: '/'
      - title: 'Спорт'
        url: '/'
      - title: 'Партнёры'
        url: '/'
      - title: 'Стипендии'
        url: '/'

# Owner/author information
owner:
  name:           Студсовет мехмата МГУ
  site:           https://vk.com/stud_mm
  avatar:         images/avatar.jpg
  twitter:
  vk:             stud_mm
  bio:            "Представляем и защищаем интересы студентов мехмата"
  email:          studcouncilmm@gmail.com
  # GitHub nick for use in follow button in author block.
  github: uburuntu

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter:

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "vk"
    url: "https://vk.com/stud_mm"
  - title: "instagram"
    url: "https://www.instagram.com/stud_mm"
  - title: "youtube"
    url: "https://www.youtube.com/channel/UCXZgEiEZ79WZKmSbQh9BbXA"

# Background image to be tiled on all pages
background: big_pattern.png

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Moscow
locale:      ru-RU
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: false

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate]
